# Generated by Django 3.0 on 2022-05-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_auto_20220513_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserve_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
